version: '3.5'
services:
  casnode:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./conf:/conf/
networks:
  my-proxy-net:
    external:
      name: custom_network
